version: "3.7"
services:
  app:
    build:
      args:
        user: Urna-Simulado
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: urna-simulado
    container_name: urna-simulado-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - urna-simulado

  nginx:
    image: nginx:alpine
    container_name: urna-simulado-nginx
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - urna-simulado

networks:
  urna-simulado:
    driver: bridge
